---
  - hosts: all
    become: true
    pre_tasks:


    - name: INSTALL UPDATES (CentOS)
      yum:
        update_cache: yes
        update_only: yes
      when: ansible_distribution == "CentOS"

    - name: INSTALL UPDATES (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

  - hosts: ubuntu
    become: true
    tasks:


    -  name: Install Docker in Ubuntu
       apt:
         name: docker.io

    -  name: Start and Enable Docker in Ubuntu
       systemd:
         name: docker
         state: restarted
         enabled: true

    -  name: Add User to Docker Group
       user:
         name: "{{ ansible_user }}"
         groups: docker

    -  name: Create directory for Docker in Ubuntu
       file:
         path: ~/docker
         state: directory

    -  name: Create dockerfile in Docker Directory in Ubuntu
       file:
         path: "~/docker/dockerfile"
         state: touch

    -  name: Modify dockerfile with Content in Ubuntu
       copy:
         dest: "~/docker/dockerfile"
         src: ubuntu_dockerfile

